# Generated by Django 3.2.25 on 2026-01-12 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(help_text='消息内容，推荐为多模态JSON数组，兼容纯文本'),
        ),
    ]
