# Generated by Django 3.2.25 on 2026-01-13 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_app'),
    ]

def migrate_data(apps, schema_editor):
    App = apps.get_model('chat', 'App')
    AppCategory = apps.get_model('chat', 'AppCategory')
    
    mapping = {
        'featured': '精选',
        'lifestyle': '生活方式',
        'productivity': '工作效率',
        'other': '其他'
    }
    
    cat_objs = {}
    for code, name in mapping.items():
        obj, _ = AppCategory.objects.get_or_create(name=name)
        cat_objs[code] = obj
        
    for app in App.objects.all():
        old_val = app.old_category
        if old_val in cat_objs:
            app.category = cat_objs[old_val]
            app.save()

class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_app'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='app',
            old_name='category',
            new_name='old_category',
        ),
        migrations.AddField(
            model_name='app',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apps', to='chat.appcategory'),
        ),
        migrations.RunPython(migrate_data),
        migrations.RemoveField(
            model_name='app',
            name='old_category',
        ),
    ]
