# Generated by Django 3.2.25 on 2026-01-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20260113_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='configuration',
            field=models.JSONField(blank=True, default=dict, help_text='模型参数配置 (temperature, max_tokens等)'),
        ),
        migrations.AddField(
            model_name='app',
            name='system_prompt',
            field=models.TextField(blank=True, default='', help_text='应用的系统提示词'),
        ),
        migrations.AddField(
            model_name='app',
            name='variables',
            field=models.JSONField(blank=True, default=list, help_text='提示词中定义的变量列表'),
        ),
    ]
