# Generated by Django 3.2.25 on 2026-01-14 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_make_app_type_required'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='app',
            options={'ordering': ['-created_at'], 'verbose_name': '应用', 'verbose_name_plural': '应用'},
        ),
        migrations.AlterField(
            model_name='app',
            name='category',
            field=models.ForeignKey(blank=True, help_text='应用所属分类', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apps', to='chat.appcategory'),
        ),
        migrations.AlterField(
            model_name='app',
            name='description',
            field=models.TextField(help_text='应用描述'),
        ),
        migrations.AlterField(
            model_name='app',
            name='icon_url',
            field=models.URLField(blank=True, help_text='应用图标URL', null=True),
        ),
        migrations.AlterField(
            model_name='app',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='是否为精选应用'),
        ),
        migrations.AlterField(
            model_name='app',
            name='name',
            field=models.CharField(help_text='应用名称', max_length=100),
        ),
        migrations.AlterField(
            model_name='app',
            name='system_prompt',
            field=models.TextField(blank=True, default='', help_text='应用的系统提示词，支持 {{variable}} 变量'),
        ),
        migrations.AlterField(
            model_name='app',
            name='variables',
            field=models.JSONField(blank=True, default=list, help_text="提示词中定义的变量列表，格式: [{name: 'var1', default: 'value'}]"),
        ),
    ]
