# Generated by Django 3.2.25 on 2026-01-14 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20260114_0214'),
        ('chat', '0009_update_app_parameters'),
    ]

    operations = [
    ]
