# Generated by Django 3.2.25 on 2026-01-14 02:46

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_merge_20260114_0246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='variables',
        ),
        migrations.AlterField(
            model_name='app',
            name='name',
            field=models.CharField(help_text='应用名称，必须为驼峰命名，如 GetWeather', max_length=100, validators=[chat.models.validate_camel_case_name]),
        ),
        migrations.AlterField(
            model_name='app',
            name='parameters',
            field=models.JSONField(blank=True, default=dict, help_text='Function Calling 参数定义，格式符合 OpenAI parameters schema'),
        ),
        migrations.AlterField(
            model_name='app',
            name='system_prompt',
            field=models.TextField(blank=True, default='', help_text='应用的系统提示词'),
        ),
    ]
