# Generated by Django 3.2.25 on 2026-01-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_add_thinking_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='provider_id',
            field=models.CharField(blank=True, help_text='使用的供应商ID（UUID格式）', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='llmmodel',
            name='id',
            field=models.CharField(editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='provider',
            name='id',
            field=models.CharField(editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
