# Generated by Django 3.2.25 on 2026-01-15 05:35

from django.db import migrations
import uuid


def migrate_to_uuid(apps, schema_editor):
    """将现有的整数ID迁移为UUID字符串"""
    Provider = apps.get_model('chat', 'Provider')
    LLMModel = apps.get_model('chat', 'LLMModel')
    App = apps.get_model('chat', 'App')
    
    # 创建ID映射
    provider_map = {}
    model_map = {}
    
    # 迁移Provider
    for provider in Provider.objects.all():
        old_id = provider.id
        new_id = uuid.uuid4().hex
        provider_map[str(old_id)] = new_id
        
        # 直接使用SQL更新，避免Django ORM的约束检查
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                "UPDATE chat_provider SET id = %s WHERE id = %s",
                [new_id, old_id]
            )
    
    # 迁移LLMModel
    for model in LLMModel.objects.all():
        old_id = model.id
        old_provider_id = str(model.provider_id)
        new_id = uuid.uuid4().hex
        new_provider_id = provider_map.get(old_provider_id, old_provider_id)
        model_map[str(old_id)] = new_id
        
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                "UPDATE chat_llmmodel SET id = %s, provider_id = %s WHERE id = %s",
                [new_id, new_provider_id, old_id]
            )
    
    # 迁移App中的provider_id
    for app in App.objects.all():
        if app.provider_id:
            old_provider_id = str(app.provider_id)
            new_provider_id = provider_map.get(old_provider_id)
            if new_provider_id:
                with schema_editor.connection.cursor() as cursor:
                    cursor.execute(
                        "UPDATE chat_app SET provider_id = %s WHERE id = %s",
                        [new_provider_id, app.id]
                    )


def reverse_migrate(apps, schema_editor):
    """回滚不支持，需要手动处理"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_auto_20260115_0535'),
    ]

    operations = [
        migrations.RunPython(migrate_to_uuid, reverse_migrate),
    ]
