# Generated by Django 3.2.25 on 2026-01-16 00:00

from django.db import migrations, models
from django.db.models import deletion
import uuid


def migrate_app_to_uuid(apps, schema_editor):
    """将 App 表的整数 ID 迁移为 UUID 字符串"""
    App = apps.get_model('chat', 'App')
    
    # 创建 ID 映射
    app_map = {}
    
    # 迁移 App
    for app in App.objects.all():
        old_id = app.id
        new_id = uuid.uuid4().hex
        app_map[str(old_id)] = new_id
        
        # 直接使用 SQL 更新，避免 Django ORM 的约束检查
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                "UPDATE chat_app SET id = %s WHERE id = %s",
                [new_id, old_id]
            )
    
    return app_map


def migrate_conversation_to_uuid(apps, schema_editor):
    """将 Conversation 表的整数 ID 迁移为 UUID 字符串"""
    Conversation = apps.get_model('chat', 'Conversation')
    Message = apps.get_model('chat', 'Message')
    
    # 创建 ID 映射
    conversation_map = {}
    
    # 迁移 Conversation
    for conversation in Conversation.objects.all():
        old_id = conversation.id
        new_id = uuid.uuid4().hex
        conversation_map[str(old_id)] = new_id
        
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                "UPDATE chat_conversation SET id = %s WHERE id = %s",
                [new_id, old_id]
            )
    
    # 更新 Message 中的 conversation_id 外键
    for message in Message.objects.all():
        old_conversation_id = str(message.conversation_id)
        new_conversation_id = conversation_map.get(old_conversation_id)
        if new_conversation_id:
            with schema_editor.connection.cursor() as cursor:
                cursor.execute(
                    "UPDATE chat_message SET conversation_id = %s WHERE id = %s",
                    [new_conversation_id, message.id]
                )
    
    return conversation_map


def migrate_message_to_uuid(apps, schema_editor):
    """将 Message 表的整数 ID 迁移为 UUID 字符串"""
    Message = apps.get_model('chat', 'Message')
    
    # 创建 ID 映射
    message_map = {}
    
    # 迁移 Message
    for message in Message.objects.all():
        old_id = message.id
        new_id = uuid.uuid4().hex
        message_map[str(old_id)] = new_id
        
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                "UPDATE chat_message SET id = %s WHERE id = %s",
                [new_id, old_id]
            )
    
    return message_map


def migrate_all_to_uuid(apps, schema_editor):
    """
    按顺序迁移所有表的 ID 到 UUID
    顺序很重要：先迁移被引用的表（Conversation），再迁移引用它的表（Message）
    """
    # 1. 迁移 App（独立表，无外键依赖）
    print("Migrating App IDs to UUID...")
    migrate_app_to_uuid(apps, schema_editor)
    
    # 2. 迁移 Conversation（被 Message 引用）
    print("Migrating Conversation IDs to UUID...")
    migrate_conversation_to_uuid(apps, schema_editor)
    
    # 3. 迁移 Message（引用 Conversation）
    print("Migrating Message IDs to UUID...")
    migrate_message_to_uuid(apps, schema_editor)
    
    print("All migrations completed successfully!")


def reverse_migrate(apps, schema_editor):
    """回滚不支持，需要手动处理"""
    raise NotImplementedError("Cannot reverse this migration. Please restore from backup if needed.")


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_migrate_ids_to_uuid'),
    ]

    operations = [
        # 第一步：修改字段类型为 CharField
        migrations.AlterField(
            model_name='app',
            name='id',
            field=models.CharField(editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='id',
            field=models.CharField(editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.CharField(editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(on_delete=deletion.CASCADE, related_name='messages', to='chat.conversation'),
        ),
        
        # 第二步：执行数据迁移
        migrations.RunPython(migrate_all_to_uuid, reverse_migrate),
    ]
