# Generated by Django 3.2.25 on 2026-01-19 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_migrate_app_conversation_message_to_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='execution_mode',
            field=models.CharField(choices=[('chat', 'Chat Mode (对话聊天式)'), ('task', 'Task Mode (任务执行式)')], default='chat', help_text='执行模式：chat=对话聊天式(system_prompt作为system消息)，task=任务执行式(prompt作为user消息)', max_length=10),
        ),
        migrations.AlterField(
            model_name='app',
            name='system_prompt',
            field=models.TextField(blank=True, default='', help_text='应用的提示词（chat模式下为系统提示词，task模式下为任务模板）'),
        ),
    ]
