# Generated by Django 3.2.25 on 2026-01-22 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_auto_20260119_0211'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppScenario',
            fields=[
                ('id', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='场景名称', max_length=100)),
                ('description', models.TextField(blank=True, help_text='场景描述')),
                ('parameters', models.JSONField(default=dict, help_text='场景参数集合')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='chat.app')),
            ],
            options={
                'verbose_name': '应用场景',
                'verbose_name_plural': '应用场景',
                'ordering': ['-updated_at'],
            },
        ),
    ]
