# Generated by Django 3.2.25 on 2026-03-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_appscenario'),
    ]

    operations = [
        migrations.CreateModel(
            name='TTSVoice',
            fields=[
                ('speaker', models.CharField(help_text='说话人标识符', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='语音配置名称', max_length=100, unique=True)),
                ('app_id', models.CharField(help_text='TTS 应用 ID', max_length=100)),
                ('access_key', models.CharField(help_text='TTS 访问密钥', max_length=255)),
                ('resource_id', models.CharField(help_text='TTS 资源 ID', max_length=100)),
                ('base_url', models.URLField(help_text='TTS 服务基础 URL')),
                ('is_active', models.BooleanField(default=True, help_text='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'TTS 语音配置',
                'verbose_name_plural': 'TTS 语音配置',
                'ordering': ['-updated_at'],
            },
        ),
    ]
