# Generated by Django 3.2.25 on 2026-03-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentic_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceProtocol',
            fields=[
                ('id', models.CharField(help_text='设备标准名', max_length=100, primary_key=True, serialize=False)),
                ('protocol', models.JSONField(help_text='设备协议详情')),
                ('category', models.CharField(help_text='设备品类', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'device_protocol',
                'ordering': ['category', 'id'],
            },
        ),
    ]
