# Generated by Django 3.2.25 on 2026-03-12 13:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_ttsvoice'),
        ('agentic_test', '0002_deviceprotocol'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='任务名称', max_length=200)),
                ('prd_content', models.TextField(blank=True, help_text='产品PRD或需求描述', null=True)),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '运行中'), ('completed', '已完成'), ('failed', '失败')], default='pending', help_text='任务状态', max_length=20)),
                ('report_url', models.URLField(blank=True, help_text='测试报告下载链接', null=True)),
                ('report_data', models.JSONField(blank=True, default=dict, help_text='测试报告数据')),
                ('result_summary', models.TextField(blank=True, help_text='执行结果摘要', null=True)),
                ('error_message', models.TextField(blank=True, help_text='错误信息', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='开始执行时间', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='完成时间', null=True)),
                ('iot_protocol', models.ForeignKey(blank=True, help_text='IOT设备协议', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_tasks', to='agentic_test.deviceprotocol')),
                ('tts_voice', models.ForeignKey(blank=True, help_text='TTS音色配置', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_tasks', to='chat.ttsvoice')),
            ],
            options={
                'verbose_name': '测试任务',
                'verbose_name_plural': '测试任务',
                'db_table': 'test_task',
                'ordering': ['-created_at'],
            },
        ),
    ]
