# Generated by Django 3.2.25 on 2026-03-15 15:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_ttsvoice'),
        ('agentic_test', '0003_testtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtask',
            name='tts_voice',
            field=models.ForeignKey(blank=True, help_text='TTS音色配置（已弃用，请使用employee）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_tasks', to='chat.ttsvoice'),
        ),
        migrations.CreateModel(
            name='DigitalEmployee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='数字员工名称', max_length=100)),
                ('avatar_index', models.IntegerField(choices=[(0, '橙色半圆'), (1, '紫色方块'), (2, '黑色方块'), (3, '黄色圆角')], default=0, help_text='3D角色索引 (0-3)')),
                ('is_active', models.BooleanField(default=True, help_text='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tts_voice', models.ForeignKey(help_text='关联的TTS音色', on_delete=django.db.models.deletion.PROTECT, related_name='digital_employees', to='chat.ttsvoice')),
            ],
            options={
                'verbose_name': '数字员工',
                'verbose_name_plural': '数字员工',
                'db_table': 'digital_employee',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='testtask',
            name='employee',
            field=models.ForeignKey(blank=True, help_text='执行任务的数字员工', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='agentic_test.digitalemployee'),
        ),
    ]
