# Generated by Django 3.2.25 on 2026-03-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentic_test', '0004_auto_20260315_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtask',
            name='session_id',
            field=models.CharField(blank=True, help_text='WebSocket会话ID', max_length=100, null=True),
        ),
    ]
