# Generated by Django 3.2.25 on 2026-03-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentic_test', '0005_testtask_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtask',
            name='job_instance_id',
            field=models.CharField(blank=True, help_text='任务实例ID，用于日志追踪', max_length=100, null=True, unique=True),
        ),
    ]
