# Generated by Django 3.2.25 on 2026-03-17 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentic_test', '0006_add_job_instance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtask',
            name='status',
            field=models.CharField(choices=[('pending', '待执行'), ('running', '运行中'), ('completed', '已完成'), ('failed', '失败'), ('stopped', '已停止')], default='pending', help_text='任务状态', max_length=20),
        ),
    ]
