# Generated by Django 3.2.25 on 2026-03-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentic_test', '0007_add_stopped_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceprotocol',
            name='functions_md',
            field=models.TextField(blank=True, default='', help_text='设备功能说明(Markdown格式)'),
        ),
    ]
